apiVersion: networking.k8s.io/v1
# UPDATE API
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    # REMOVE CLASSNAME ANNOTATION
    nginx.ingress.kubernetes.io/use-regex: 'true'
    # ADD ANNOTATION
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    # ADD ANNOTATION
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'

spec:
  ingressClassName: nginx
  # ADD INGRESSCLASSNAME FIELD
  tls:
    - hosts:
        - kssp.3utilities.com
        # - www.kssp.3utilities.com
      secretName: kssp-3utilities-com
  rules:
    - host : kssp.3utilities.com
      http:
        paths:
          - path: /?(.*)
            # UPDATE PATH
            pathType: ImplementationSpecific
            # ADD PATHTYPE
            backend:
              service:
                # UPDATE SERVICE FIELDS
                name: client-cluster-ip
                port:
                  number: 3000
          - path: /api/?(.*)
            # UPDATE PATH
            pathType: ImplementationSpecific
            # ADD PATHTYPE
            backend:
              service:
                # UPDATE SERVICE FIELDS
                name: server-cluster-ip
                port:
                  number: 5000
    # - host : www.kssp.3utilities.com
    #   http:
    #     paths:
    #       - path: /?(.*)
    #         # UPDATE PATH
    #         pathType: ImplementationSpecific
    #         # ADD PATHTYPE
    #         backend:
    #           service:
    #             # UPDATE SERVICE FIELDS
    #             name: client-cluster-ip
    #             port:
    #               number: 3000
    #       - path: /api/?(.*)
    #         # UPDATE PATH
    #         pathType: ImplementationSpecific
    #         # ADD PATHTYPE
    #         backend:
    #           service:
    #             # UPDATE SERVICE FIELDS
    #             name: server-cluster-ip
    #             port:
    #               number: 5000
