name: Deploy MultiK8s
on:
  push:
    branches:
      - main

env:
  SHA: $(git rev-parse HEAD)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Test
        run: |-
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker build -t ksspam/react-test -f ./client/Dockerfile.dev ./client
          docker run -e CI=true ksspam/react-test npm test

      - name: Set Service Key
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GKE_SA_KEY }}'

      - name: Set Project
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: multi-k8s-460417

      - name: Auth
        run: |-
          gcloud --quiet auth configure-docker

      - name: Get Credentials
        uses: google-github-actions/get-gke-credentials@v0
        with:
          cluster_name: multi-cluster
          location: us-central1-c

      - name: Build
        run: |-
          docker build -t ksspam/multi-client-up:latest -t ksspam/multi-client-up:${{ env.SHA }} -f ./client/Dockerfile ./client
          docker build -t ksspam/multi-server-up:latest -t ksspam/multi-server-up:${{ env.SHA }} -f ./server/Dockerfile ./server
          docker build -t ksspam/multi-worker-up:latest -t ksspam/multi-worker-up:${{ env.SHA }} -f ./worker/Dockerfile ./worker

      - name: Push
        run: |-
          docker push ksspam/multi-client-up:latest
          docker push ksspam/multi-server-up:latest
          docker push ksspam/multi-worker-up:latest

          docker push ksspam/multi-client-up:${{ env.SHA }}
          docker push ksspam/multi-server-up:${{ env.SHA }}
          docker push ksspam/multi-worker-up:${{ env.SHA }}

      - name: Apply
        run: |-
          kubectl apply -f k8s
          kubectl set image deployments/server-deployment server=ksspam/multi-server-up:${{ env.SHA }}
          kubectl set image deployments/client-deployment client=ksspam/multi-client-up:${{ env.SHA }}
          kubectl set image deployments/worker-deployment worker=ksspam/multi-worker-up:${{ env.SHA }}
